// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DMGestionDeTareas.Migrations
{
    [DbContext(typeof(DMGestionDeTareasContext))]
    partial class DMGestionDeTareasContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DMGestionDeTareas.Models.DMCategoria", b =>
                {
                    b.Property<int>("DMCategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DMCategoriaId"));

                    b.Property<string>("DMDescripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DMNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DMTareaId")
                        .HasColumnType("int");

                    b.HasKey("DMCategoriaId");

                    b.HasIndex("DMTareaId");

                    b.ToTable("DMCategoria");
                });

            modelBuilder.Entity("DMGestionDeTareas.Models.DMPrioridad", b =>
                {
                    b.Property<int>("DMPrioridadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DMPrioridadId"));

                    b.Property<string>("DMDescripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DMNombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DMTareaId")
                        .HasColumnType("int");

                    b.HasKey("DMPrioridadId");

                    b.HasIndex("DMTareaId");

                    b.ToTable("DMPrioridad");
                });

            modelBuilder.Entity("DMGestionDeTareas.Models.DMTarea", b =>
                {
                    b.Property<int>("DMTareaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DMTareaId"));

                    b.Property<int>("DMCategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("DMDescripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DMFechaVencimiento")
                        .HasColumnType("datetime2");

                    b.Property<int>("DMPrioridadId")
                        .HasColumnType("int");

                    b.Property<string>("DMTitulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DMTareaId");

                    b.HasIndex("DMCategoriaId");

                    b.HasIndex("DMPrioridadId");

                    b.ToTable("DMTarea");
                });

            modelBuilder.Entity("DMGestionDeTareas.Models.DMCategoria", b =>
                {
                    b.HasOne("DMGestionDeTareas.Models.DMTarea", null)
                        .WithMany("DMCategorias")
                        .HasForeignKey("DMTareaId");
                });

            modelBuilder.Entity("DMGestionDeTareas.Models.DMPrioridad", b =>
                {
                    b.HasOne("DMGestionDeTareas.Models.DMTarea", null)
                        .WithMany("DMPrioridades")
                        .HasForeignKey("DMTareaId");
                });

            modelBuilder.Entity("DMGestionDeTareas.Models.DMTarea", b =>
                {
                    b.HasOne("DMGestionDeTareas.Models.DMCategoria", "DMCategoria")
                        .WithMany()
                        .HasForeignKey("DMCategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DMGestionDeTareas.Models.DMPrioridad", "DMPrioridad")
                        .WithMany()
                        .HasForeignKey("DMPrioridadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DMCategoria");

                    b.Navigation("DMPrioridad");
                });

            modelBuilder.Entity("DMGestionDeTareas.Models.DMTarea", b =>
                {
                    b.Navigation("DMCategorias");

                    b.Navigation("DMPrioridades");
                });
#pragma warning restore 612, 618
        }
    }
}
